### ISSUE TITLE
Script muss auf Dual-band Geräten beide SSIDs ändern

### ISSUE THREAD

**Issue by Tarnatos** [Freifunk-Nord/gluon-ssid-changer#1]
CC:
@rubo77 

https://github.com/Freifunk-Nord/gluon-ssid-changer/blob/master/files/lib/gluon/ssid-changer/ssid-changer.sh
Zeile 29:

Füge dahinter ein:
uci set wireless.client_radio1.ssid="$OFFLINE_SSID"

Die Frage ist nur wie schreibt man das ins Script ohne das es bei Single-Band Geräten einfach abbricht?

**Comment by rubo77** [comment]
Unwichtig. Eine Warnung reicht doch

**Comment by Tarnatos** [comment]
Verstehe nicht. Warnung?

Fügt man die Zeile nicht ein senden Dualband Geräte auf 5Ghz trotzdem Nord.freifunk.net

Auf singleband Geräten gibt es allerdings ne Fehlermeldung weil es kein radio1 gibt. Läuft das Script dann weiter oder bricht es ab?

**Comment by rubo77** [comment]
Musst dem Wert vorher checken, schau mal, wir der Hostname ausgelesen wird.
Analog so irgendwie

**Comment by Tarnatos** [comment]
Sorry aber das ist jenseits meiner Fähigkeiten.

**Comment by rubo77** [comment]
fixed
