### ISSUE TITLE
Default von Site Conf wird nicht übernommen

### ISSUE THREAD

**Issue by rubo77** [Freifunk-Nord/gluon-ssid-changer#15]
Beim letzten Branch hat es noch keinen Effekt, wenn man in der Site Default False wählt

**Comment by rubo77** [comment]
Erstmal ist der immer aktiv

**Comment by kaechele** [comment]
Fixed with 222b96a30259a03ca8ecdb173d9d326077a6efec

**Comment by rubo77** [comment]
Don't we have to fix the 2017 branch somehow too?

with a similar solution to the one of @ecsv

related: https://github.com/Freifunk-Nord/gluon-ssid-changer/commit/772e9f0716224388c416bbe3ff7cc6f16e0b0b52#diff-f74fa26a10b8d01f84115ef4865bb487R10

https://github.com/Freifunk-Nord/gluon-ssid-changer/issues/17
