### ISSUE TITLE
take into account different ssid for 2.4g and 5g

### ISSUE THREAD

**Issue by viisauksena** [Freifunk-Nord/gluon-ssid-changer#2]
some people discussed heavily having different ssid for 2.4 and 5g to enforce 5g where possible. you may want to to differentiate this

**Comment by Tarnatos** [comment]
Not neccessary in nord, because we use the same ssid for both frequencies.

**Comment by rubo77** [comment]
But the issue should stay open. 

Good Point, and others might use our branch of the ssid-changer.

We should impement this, if someone needs it cause they have different ssids.

**Comment by rubo77** [comment]
there is a solution here: https://github.com/tennet-ahertel/gluon-ssid-changer/commit/33676f6c0594a96893d1fe0118ad5a2a0949cd34

It should just change the separator-character from `'` to `~` instead, cause we already use that separator for the `sed` command

**Comment by tennet-ahertel** [comment]
Solution with ~ is here: https://github.com/tennet-ahertel/gluon-ssid-changer/commit/8c8116bf74578c138c77e6eb2e60303b805b1cae

**Comment by rubo77** [comment]
@tennet-ahertel : will you create a Pull Request?

**Comment by rubo77** [comment]
fixed by #18
